### ISSUE TITLE
[Assigned] android.view.InflateException: Binary XML file line #199: Error inflating class TextView

### ISSUE THREAD

**Issue by Pluu** [DroidKaigi/conference-app-2018#307]
## Overview (Required)
- CalligraphyLayoutInflater a crash

### Test Device Configurate

- Android 4.4.2 (API 19)
- Crash Rate : 100%

I could not get all logs.

```
01-19 18:13:34.840 E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.github.droidkaigi.confsched2018.debug, PID: 3152
android.view.InflateException: Binary XML file line #199: Error inflating class TextView
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
     at com.xwray.groupie.GroupAdapter.onCreateViewHolder(GroupAdapter.java:77)
     at com.xwray.groupie.GroupAdapter.onCreateViewHolder(GroupAdapter.java:19)
     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1514)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1514)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1514)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1673)
     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
     at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
     at android.view.View.layout(View.java:14858)
     at android.view.ViewGroup.layout(ViewGroup.java:4646)
     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1673)
     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
     at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
     at android.view.View.layout(View.java:14858)
 	at android.view.ViewGrou
```

**Comment by takahirom** [comment]
That's by my library 😭 
I will fix it 👍

**Comment by takahirom** [comment]
I think it is not library crash 🤔

**Comment by takahirom** [comment]
```
I think this error is occurred by inserting a vector-drawable resource to a TextView directly by android:drawableStart.
It needs to convert to a StateListDrawable before insert.
```

**Comment by takahirom** [comment]
I think we can use StateListDrawable with BindingAdapter
like this

```
app:drawableStart="@{@drawble/hogehoge}"

fun TextView.drawbleStart(drawable : Drawble) {
  setCompoundDrawable(new StateListDrawable(drawable)....)
}
```

**Comment by takahirom** [comment]
If you have time, please contribute this🙏

**Comment by Pluu** [comment]
Test result 
```
// item_speech_session.xml
"android:drawableStart="@drawable/ic_check_circle_black_24dp"
```
If you delete it, the crash disappears.

**Comment by konifar** [comment]
@Pluu Thanks! `drawableStart` doesn't support vector drawable. That's the reason?

**Comment by Pluu** [comment]
@konifar Yes. I think that the cause of the current situation is that.

link : https://qiita.com/konifar/items/bf581b8f23dea7b30f85#2-textviewのandroiddrawableleft

**Comment by Pluu** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
@Pluu Thanks 👍 Assigned

**Comment by Pluu** [comment]
@takahirom I'm sorry to judge mistakenly as `CalligraphyLayoutInflater`.
