### ISSUE TITLE
Crash at MainActivity on kitkat

### ISSUE THREAD

**Issue by nacatl** [DroidKaigi/conference-app-2018#370]
## Overview (Required)
- On a device as Kitkat, the app crashes at the time of inflate the item_speech_session.xml with the error message below.
(Generally the error occurs with opening MainActivity...)

```
io.github.droidkaigi.confsched2018.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: io.github.droidkaigi.confsched2018.debug, PID: 4668
                                                                                        android.view.InflateException: Binary XML file line #199: Error inflating class TextView
                                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                            at com.xwray.groupie.GroupAdapter.onCreateViewHolder(GroupAdapter.java:77)
                                                                                            at com.xwray.groupie.GroupAdapter.onCreateViewHolder(GroupAdapter.java:19)
                                                                                            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                                            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                                            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                                            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                                            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1514)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1514)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1514)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4704)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                            at android.view.View.layout(View.java:15004)
                                                                                        	at android.view.ViewGrou
```
(The last 'ViewGrou' is not miss-paste, this is end. I think because the text is too long to display.)

I think this error is occurred by inserting a vector-drawable resource to a TextView directly by `android:drawableStart`.  
It needs to convert to a StateListDrawable before insert.

## Links
- https://qiita.com/konifar/items/bf581b8f23dea7b30f85#2-textview%E3%81%AEandroiddrawableleft

**Comment by nacatl** [comment]
I'm sorry...
This is duplicated with #368 and #307 .

In this case, should I close this?

**Comment by takahirom** [comment]
This information is the best information 💯 Thanks!!

```
I think this error is occurred by inserting a vector-drawable resource to a TextView directly by android:drawableStart.
It needs to convert to a StateListDrawable before insert.
```

**Comment by nacatl** [comment]
Thank you for reply and correspondence!!
