### ISSUE TITLE
[Assigned] ClassNotFoundException occurs when the notification time is reached.

### ISSUE THREAD

**Issue by nukka123** [DroidKaigi/conference-app-2018#456]
## Overview (Required)

The reproduction procedure is as follows.

1. Launch droidkaigi2018 app. 
1-2. Enable Favorites for any sessions. (ex. DAY1 / 10:20-10:50)
1-3. Finish  droidkaigi2018 app. (back key)
2. Visit Settings app.
2-1. Data & time >  set to Feb 8, 2018 10:09 (GMT+09:00)
3. Reach at Feb 8, 2018 10:10 (GMT+09:00)
-> ClassNotFoundException occurs 

Also, it worked normally when testing with Debot.

I Tested Emulator(API27).

### Logcat 
```
02-08 21:52:33.599 1526-1582/? W/Intent: Failure filling in extras
                                         java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = io.github.droidkaigi.confsched2018.util.NotificationUtil$ChannelType)
                                             at android.os.Parcel.readSerializable(Parcel.java:3010)
                                             at android.os.Parcel.readValue(Parcel.java:2796)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:3114)
                                             at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:226)
                                             at android.os.Bundle.putAll(Bundle.java:288)
                                             at android.content.Intent.fillIn(Intent.java:9112)
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:264)
                                             at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:240)
                                             at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7726)
                                             at android.app.PendingIntent.send(PendingIntent.java:874)
                                             at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3122)
                                             at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2523)
                                             at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2646)
                                          Caused by: java.lang.ClassNotFoundException: io.github.droidkaigi.confsched2018.util.NotificationUtil$ChannelType
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:453)
                                             at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:629)
                                             at android.os.Parcel$2.resolveClass(Parcel.java:3001)
                                             at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616)
                                             at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
                                             at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1729)
                                             at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
                                             at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374)
                                             at android.os.Parcel.readSerializable(Parcel.java:3004)
                                             at android.os.Parcel.readValue(Parcel.java:2796) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:3114) 
                                             at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:226) 
                                             at android.os.Bundle.putAll(Bundle.java:288) 
                                             at android.content.Intent.fillIn(Intent.java:9112) 
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:264) 
                                             at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:240) 
                                             at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7726) 
                                             at android.app.PendingIntent.send(PendingIntent.java:874) 
                                             at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3122) 
                                             at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2523) 
                                             at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2646) 
                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "io.github.droidkaigi.confsched2018.util.NotificationUtil$ChannelType" on path: DexPathList[[zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar", zip file "/system/framework/com.android.location.provider.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]
                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:453) 
                                             at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:629) 
                                             at android.os.Parcel$2.resolveClass(Parcel.java:3001) 
                                             at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616) 
                                             at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521) 
                                             at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1729) 
                                             at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) 
                                             at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374) 
                                             at android.os.Parcel.readSerializable(Parcel.java:3004) 
                                             at android.os.Parcel.readValue(Parcel.java:2796) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:3114) 
                                             at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:226) 
                                             at android.os.Bundle.putAll(Bundle.java:288) 
                                             at android.content.Intent.fillIn(Intent.java:9112) 
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:264) 
                                             at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:240) 
                                             at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7726) 
                                             at android.app.PendingIntent.send(PendingIntent.java:874) 
                                             at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3122) 
                                             at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2523) 
                                             at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2646) 
02-08 21:52:34.218 12164-12164/? D/NotificationBroadcastReceiver: NotificationBroadcastReceiver.onReceive
02-08 21:52:34.218 12164-12164/? D/NotificationBroadcastReceiver: Show Notification
02-08 21:52:34.218 12164-12164/? D/AndroidRuntime: Shutting down VM
02-08 21:52:34.220 12164-12164/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: io.github.droidkaigi.confsched2018.debug, PID: 12164
                                                   java.lang.RuntimeException: Unable to start receiver io.github.droidkaigi.confsched2018.presentation.common.broadcastreceiver.NotificationBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type io.github.droidkaigi.confsched2018.util.NotificationUtil.ChannelType
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
                                                       at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                    Caused by: kotlin.TypeCastException: null cannot be cast to non-null type io.github.droidkaigi.confsched2018.util.NotificationUtil.ChannelType
                                                       at io.github.droidkaigi.confsched2018.presentation.common.broadcastreceiver.NotificationBroadcastReceiver.onReceive(NotificationBroadcastReceiver.kt:30)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
                                                       at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                       at android.os.Looper.loop(Looper.java:164) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

## Links
-

**Comment by nukka123** [comment]
Probably related articles.
https://stackoverflow.com/questions/11258537/broadcastreceiver-classnotfound-exception
https://issuetracker.google.com/issues/36914697

**Comment by takahirom** [comment]
Probably we should pass channel information with `channelType.id` and find it.
https://github.com/DroidKaigi/conference-app-2018/blob/1daf58a4bab56586f13c95a263f9ddc2f040c701/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/broadcastreceiver/NotificationBroadcastReceiver.kt#L30

**Comment by nukka123** [comment]
@takahirom 
I will try it.

**Comment by takahirom** [comment]
Thanks 👍 Assigned

**Comment by takahirom** [comment]
We are so helped! Are you a firefighter?🔥🚒
