### ISSUE TITLE
[Assigned] Crash at Session Detail screen upon activity state loss

### ISSUE THREAD

**Issue by miga9** [DroidKaigi/conference-app-2018#542]
## Overview (Required)
Steps to reproduce:
- Navigate to any Session Detail screen.
- Put the app in background by tapping on device home button.
- Perform a bunch of other actions to put the device in low memory situation to trigger state loss.
- Open the app when you think you did enough.
- Crash.

Stacktrace:
`01-30 21:54:37.382 7569-7569/io.github.droidkaigi.confsched2018.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: io.github.droidkaigi.confsched2018.debug, PID: 7569
                                                                                        java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter speakers
                                                                                            at io.github.droidkaigi.confsched2018.presentation.common.view.SpeakersSummaryLayout.setSpeakers(SpeakersSummaryLayout.kt)
                                                                                            at io.github.droidkaigi.confsched2018.databinding.FragmentSessionDetailBinding.executeBindings(FragmentSessionDetailBinding.java:386)
                                                                                            at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:379)
                                                                                            at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:351)
                                                                                            at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:178)
                                                                                            at android.databinding.ViewDataBinding$5.onViewAttachedToWindow(ViewDataBinding.java:146)
                                                                                            at android.view.View.dispatchAttachedToWindow(View.java:15520)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by takahirom** [comment]
Thanks 👍 
I was able to reproduce the crash by enabling the "Do not keep activities" option on it

**Comment by takahirom** [comment]
Probably We can use nullable for `setSpeakers()` parameter. And early return `speakers ?: return`

**Comment by panpanini** [comment]
Can I have a look at this issue? 🙋

**Comment by takahirom** [comment]
@panpanini Thanks :+1:
